### ISSUE TITLE
w3 contract add

### ISSUE THREAD

**Issue by pavondunbar** [coccoinomane/web3cli#19]
Hello there,

First, great project!  I appreciate it!

I'm trying to run this command to add my contract, but the ABI part is what is throwing me off.

Here is the command I am running:

`w3 contract add Intermezzo 0x34Dc8f1F1A616664112edeb6d4b4a7cC6E916A96 --abi [{"inputs":[{"internalType":"address","name":"_usdcAddress","type":"address"}],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[],"name":"COLLATERAL_RATIO","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function","constant":true},{"inputs":[],"name":"MAX_SUPPLY","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function","constant":true},{"inputs":[],"name":"TARGET_PRICE","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function","constant":true},{"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"balances","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function","constant":true},{"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"collateralBalances","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function","constant":true},{"inputs":[],"name":"decimals","outputs":[{"internalType":"uint8","name":"","type":"uint8"}],"stateMutability":"view","type":"function","constant":true},{"inputs":[],"name":"name","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function","constant":true},{"inputs":[],"name":"symbol","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function","constant":true},{"inputs":[],"name":"totalCollateral","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function","constant":true},{"inputs":[],"name":"totalSupply","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function","constant":true},{"inputs":[],"name":"usdc","outputs":[{"internalType":"contract IERC20","name":"","type":"address"}],"stateMutability":"view","type":"function","constant":true},{"inputs":[{"internalType":"uint256","name":"collateralAmount","type":"uint256"}],"name":"purchaseCollateral","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"redeemCollateral","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"stabilizePrice","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"withdrawExcessCollateral","outputs":[],"stateMutability":"nonpayable","type":"function"}] --chain opera`

However, the command just "hangs".  At the end there is a [PROCESS COMPLETED] message but it does not return me back to my command prompt in the terminal.

Does it need time to import the ABI functions or something?

Please advise.  I am trying to access the contract's functions so I can interact with it.

Thanks again!

Pavon

**Comment by pavondunbar** [comment]
Nevermind, I got it to work.  I'm suppoed to put the abi as a string by placing it within the ''.

Thanks!

Closing this issue.

**Comment by coccoinomane** [comment]
Thanks @pavondunbar for posting your solution!  Yes, when passing the ABI via terminal, you need to enclose it with single quotes `'`.

I did not know about the `opera` blockchain.  Is there an official RPC?  So that I can add it to web3cli :-)

**Comment by pavondunbar** [comment]
Hello there,

Opera is just a name I passed as an argument to add the Fantom testnet to web3cli.

This is amazing!  Thank you for creating this tool!  I appreciate it!

I wanted to ask...will you be adding a feature to **verify smart contracts** after deployment?

Something like 'w3 contract verify {CONTRACT NAME} {CONTRACT ADDRESS} -c {CHAIN}

Just curious...enjoy your day!

Pavon
